var g=[],m=[],r={used:{source:"prov:entity",target:"prov:activity"},wasGeneratedBy:{source:"prov:activity",target:"prov:entity"},wasDerivedFrom:{source:"prov:usedEntity",target:"prov:generatedEntity"},wasInformedBy:{source:"prov:informant",target:"prov:informed"}},x=d3.scale.j(),y=d3.select("div#graph").append("svg").a("width",400).a("height",200),z=d3.o.l().k(-20).p(120).size([400,200]),C={},D=window.location.search.substr(1).split("&");console.log("qs",D);
D.forEach(function(b){b=b.split("=");k=b[0];v=b[1];console.log(k,v);C[k]=v});console.log("query: ",C);var E=C.source,E=E||"document.json";
d3.n(E,function(b){function F(a,b){if(void 0!=a.depth)return a.depth;a.depth="entity"==a.type?Math.floor(b+1):b+.5;console.log("WALKING",a,a.depth);var t=a.depth,p;for(p in a.e)var c=F(a.e[p],a.depth),t=c>t?c:t;return t}function I(a){var b=g,c=256/a;160<c&&(c=160);var p=c*Math.sqrt(3)/2;console.log(72,100,256,c,p);for(var d in b){var e=b[d];e.x=72+(a-e.depth)*c;e.y="entity"==e.type?100-p/2:100+p/2;e.fixed=!0}}function J(a){d3.select("#detail-header").text(a.type);d3.select("#detail").d("*").remove();
y.d("#selection").remove()}function A(a){d3.select("#detail-header").text(a.label);var b=d3.select("#detail");b.d("*").remove();var c="foundry:UUID foundry:creationTime prov:startTime prov:endTime foundry:how foundry:label foundry:version".split(" "),e;for(e in c){var d=c[e],f=d.split(":")[1];if(void 0!=a[d]){var h=b.append("tr");h.append("td").text(f);h.append("td").text(a[d])}}y.d("#selection").remove();y.m("circle",":first-child").a("r",21).style("fill","url(#selected-gradient)").a("cx",a.x).a("cy",
a.y).a("id","selection")}console.log("data loaded:",b);var n={},f=0,G={},u=[],c;for(c in b.b){b.b[c].raw=JSON.stringify(b.b[c],null," ");b.b[c].id=c;b.b[c].type="activity";var l=Date.parse(b.b[c]["prov:startTime"]);b.b[c].timecode=l;b.b[c].group=f;b.b[c].incoming=[];b.b[c].outgoing=[];b.b[c].label=b.b[c]["prov:type"].$;f=(f+1)%10;n[c]=c;u.push(b.b[c])}u.sort(function(a,b){return a.g<b.g?-1:a.g>b.g?1:0});console.log("activities:",u);c=[];var l={},d;for(d in b.c){b.c[d].raw=JSON.stringify(b.c[d],null,
" ");b.c[d].id=d;b.c[d].type="entity";var h=b.c[d]["foundry:UUID"],B=h+"@"+b.c[d]["foundry:creationTime"],w=G[h];void 0==w&&(w=f,G[h]=w,f=(f+1)%10);b.c[d].group=w;b.c[d].incoming=[];b.c[d].outgoing=[];h=b.c[d]["foundry:label"].split("/");h=h[h.length-1];b.c[d].label=h.substring(0,h.length-1);void 0==l[B]?(c.push(b.c[d]),l[B]=d,n[d]=d):n[d]=l[B]}g=u.concat(c);console.log("nodes:",g);if(!(0<function(){for(var a in r){var c=b[a];if(c)for(var e in c){var d=c[e],f=d[r[a].source],h=d[r[a].target];if(void 0==
f||void 0==n[f])return console.log("FAILURE: UNRECOGNIZED SOURCE",f,"IN EDGE",d),1;f=n[f];if(void 0==h||void 0==n[h])return console.log("FAILURE: UNRECOGNIZED TARGET",h,"IN",a,"EDGE",d),1;for(var h=n[h],l=d=void 0,q=0;q<g.length;q++)g[q].id==f?d=g[q]:g[q].id==h&&(l=g[q]);if(void 0==d)return console.log("FAILURE; COULD NOT RESOLVE SOURCE",f),1;if(void 0==l)return console.log("FAILURE; COULD NOT RESOLVE TARGET",h),1;m.push({source:d,target:l,type:a});d.h.push(l);l.e.push(d)}}return 0}(b))){console.log("links",
m);var f=void 0,e;for(e in g)if(console.log(g[e].id,"in:",g[e].e.length,"out:",g[e].h.length),0==g[e].h.length)if(console.log("ROOT FOUND",g[e]),void 0==f)f=g[e];else return console.log("FAILURE: MULTIPLE ROOTS DETECTED"),2;if(void 0==f)return console.log("FAILURE: NO ROOT FOUND"),2;console.log("ROOT",f);e=F(f,-1);console.log("MAX_DEPTH",e);I(e);z.q(g).links(m).start();y.append("svg:defs").append("svg:marker").a("id","end-arrow").a("viewBox","0 -5 10 10").a("refX",6).a("markerWidth",6).a("markerHeight",
6).a("orient","auto").append("svg:path").a("d","M0,-5L10,0L0,5").a("fill","#000");e=y.select("defs").append("radialGradient").a("id","selected-gradient");e.append("stop").a("offset","65%").a("stop-color","#F00");e.append("stop").a("offset","100%").a("stop-color","#FFF");var H=y.d(".node").data(g);e=H.i().append("g").a("class","node").a("transform",function(a){return"translate("+a.x+","+a.y+")"});e.filter(function(a){return"activity"==a.type}).append("circle").a("r",15).style("fill",function(a){return x(a.group)}).f("mouseover",
A);e.filter(function(a){return"entity"==a.type}).append("rect").a("width",26).a("height",26).a("transform","translate(-13,-13)").style("fill",function(a){return x(a.group)}).f("mouseover",A);e.append("text").text(function(a){return a.label}).a("dy",function(a){return"entity"==a.type?-19:27}).a("text-anchor","middle").a("font-weight","100").a("letter-spacing","1px");var K=y.d(".link").data(m).i().append("path").a("class","link").a("stroke-dasharray",function(a){return"wasDerivedFrom"==a.type?"5,5":
""}).a("marker-end","url(#end-arrow)").f("mouseover",J);z.f("tick",function(){K.a("d",function(a){var b=a.target.x-a.source.x,c=a.target.y-a.source.y,d=Math.sqrt(b*b+c*c),b=b/d,c=c/d;return"M"+(a.source.x+15*b)+","+(a.source.y+15*c)+"L"+(a.target.x-17*b)+","+(a.target.y-17*c)});H.a("transform",function(a){return"translate("+a.x+","+a.y+")"})});console.log("selecting last entity",g[g.length-1]);A(g[g.length-1])}});